### ISSUE TITLE
Match imputed HU to Census

### ISSUE THREAD

**Issue by hanase** [psrc/urbansim-baseyear-prep#5]

**Comment by hanase** [comment]
The matching should be done to the 2014 OFM data. Should it be matched to households or housing units?

**Comment by pcaballero** [comment]
I believe it should be matched to housing units.

**Comment by hanase** [comment]
OK - thanks. I confirmed that in the OFM data there is no case where HU < HH, so we could use that. However, what if our 2014 HU is:
 HH_ofm < HU_ours < HU_ofm
It would mean we are OK to place households, so we would not necessarily need to increase HUs. If it's the case, we could just use HH_ofm for the matching.
